new_git_repository(
    name = "googletest",
    build_file = "gtest.BUILD",
    remote = "https://github.com/google/googletest",
    tag = "release-1.8.0",
)

local_repository(
    name = "bazel_clang",
    path = "../bazel_clang",
)
